const ERRORS = {
  CREATE_FILE: 'CREATE_FILE',
  REMOVE_FILE: 'REMOVE_FILE',
  CREATE_FOLDER: 'CREATE_FOLDER',
  REMOVE_FOLDER: 'REMOVE_FOLDER',
  DOWNLOAD_REPOSITORY: 'DOWNLOAD_REPOSITORY',
  UPDATE_BRANCH: 'UPDATE_BRANCH',
};

module.exports = ERRORS;
